### ISSUE TITLE
reikna import error

### ISSUE THREAD

**Issue by TasseDeCafe** [Chakazul/Lenia#14]
Hi!

First of all, thank you for making this. It's truly amazing. I'm trying to make the Python code run on my computer, but after installing the requirements I'm getting this strange error. Any idea what's going on here?

```
Traceback (most recent call last):
  File "/home/xxx/PycharmProjects/Lenia/Python/LeniaND.py", line 4, in <module>
    import reikna.fft, reikna.cluda  # pip3 install pyopencl/pycuda, reikna
  File "/home/xxx/PycharmProjects/Lenia/venv/lib/python3.8/site-packages/reikna/fft/__init__.py", line 15, in <module>
    from reikna.fft.fft import FFT
  File "/home/xxx/PycharmProjects/Lenia/venv/lib/python3.8/site-packages/reikna/fft/fft.py", line 11, in <module>
    TEMPLATE = helpers.template_for(__file__)
  File "/home/xxx/PycharmProjects/Lenia/venv/lib/python3.8/site-packages/reikna/helpers/__init__.py", line 158, in template_for
    return make_template(name + '.mako', filename=True)
  File "/home/xxx/PycharmProjects/Lenia/venv/lib/python3.8/site-packages/reikna/helpers/__init__.py", line 100, in make_template
    return Template(**kwds)
  File "/home/xxx/PycharmProjects/Lenia/venv/lib/python3.8/site-packages/mako/template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/xxx/PycharmProjects/Lenia/venv/lib/python3.8/site-packages/mako/template.py", line 413, in _compile_from_file
    code, module = _compile_text(
  File "/home/xxx/PycharmProjects/Lenia/venv/lib/python3.8/site-packages/mako/template.py", line 711, in _compile_text
    code = compile(source, cid, 'exec')
  File "_home_xxxx_PycharmProjects_Lenia_venv_lib_python3_8_site_packages_reikna_fft_fft_mako", line 148
    def render_insertGlobalLoadsNoIf(context,input,kweights,a_indices,g_indices,pad=,fft_index_offsets=):
                                                                                    ^
SyntaxError: invalid syntax

```

**Comment by TasseDeCafe** [comment]
Nevermind, I updated the module. It wasn't compatible with Python 3.8.
